name: 'Pack Build'
description: 'Pack build images'

inputs:
  tag:
    description: 'location to write image'
    required: true
  bp_go_targets:
    description: 'value of BP_GO_TARGETS env'
  builder:
    description: 'builder image'
    required: true
    default: 'paketobuildpacks/builder-jammy-tiny'
  pack_version:
    description: 'version of pack to use'
    required: true
  additional_pack_args:
    description: 'additional args for pack'

runs:
  using: "composite"
  steps:
  - name: setup-pack
    uses: buildpacks/github-actions/setup-pack@v5.0.0
    with:
      pack-version: ${{ inputs.pack_version }}
  - name: build
    shell: bash
    run: |
      mkdir report
      
      export PATH="$PATH:$(pwd)"
      pack build ${{ inputs.tag }} \
        --builder ${{ inputs.builder }} \
        --env BP_GO_TARGETS="${{ inputs.bp_go_targets }}" \
        --report-output-dir . \
        --cache-image ${{ inputs.tag }}-cache \
        --publish ${{ inputs.additional_pack_args }}
      
      mkdir images
      digest=$(go run .github/actions/pack-build/report.go -path ./report.toml)
      name=$(basename ${{ inputs.tag }})
      echo "${{ inputs.tag }}@${digest}" > images/$name
      cat images/$name
  - name: Upload Image Artifacts
    uses: actions/upload-artifact@v3
    with:
      name: images
      path: images/
